const item = {
  isSuccess: true,
  code: '200',
  message: 'TechBook 목록 조회를 성공했습니다.',
  data: {
    content: [
      {
        id: 1,
        title: '니모를 찾아서',
        writer: 'nickname1',
        price: 10000,
        techBookThumbnailUrl: '/images/education-image1.png',
        createdAt: '2024-04-03',
        likeCount: 23,
      },
      {
        id: 2,
        title: '한 입 크기로 잘라먹는 타입스크립트(TypeScript)',
        writer: 'nickname1',
        price: 12000,
        techBookThumbnailUrl: '/images/education-image1.png',
        createdAt: '2022-04-01',
        likeCount: 10,
      },
      {
        id: 3,
        title: '비전공자도 이해할 수 있는 AWS 입문/실전',
        writer: 'nickname1',
        price: 14000,
        techBookThumbnailUrl: '/images/education-image1.png',
        createdAt: '2025-04-03',
        likeCount: 11,
      },
      {
        id: 4,
        title: '딥러닝 CNN 완벽 가이드 - Pytorch 버전',
        writer: 'nickname1',
        price: 16000,
        techBookThumbnailUrl: '/images/education-image1.png',
        createdAt: '2023-05-03',
        likeCount: 10,
      },
      {
        id: 5,
        title: '[2024 업데이트] UX/UI 시작하기 : Figma 입문 (Inflearn Original)',
        writer: 'nickname1',
        price: 18000,
        techBookThumbnailUrl: '/images/education-image1.png',
        createdAt: '2025-04-22',
        likeCount: 25,
      },
      {
        id: 6,
        title: '갖고노는 MySQL 데이터베이스 by 얄코',
        writer: 'nickname1',
        price: 20000,
        techBookThumbnailUrl: '/images/education-image1.png',
        createdAt: '2024-08-14',
        likeCount: 27,
      },
      {
        id: 7,
        title: '하루만에 오픽 IH 달성하기',
        writer: 'nickname2',
        price: 10000,
        techBookThumbnailUrl: '/images/education-image1.png',
        createdAt: '2021-07-05',
        likeCount: 77,
      },
      {
        id: 8,
        title: '아키텍처와 함께하는 GCP (Google Cloud Platform)',
        writer: 'nickname2',
        price: 12000,
        techBookThumbnailUrl: '/images/education-image1.png',
        createdAt: '2023-12-03',
        likeCount: 62,
      },
      {
        id: 9,
        title: '맛집 지도앱 만들기 (React Native + NestJS)',
        writer: 'nickname2',
        price: 14000,
        techBookThumbnailUrl: '/images/education-image1.png',
        createdAt: '2028-04-03',
        likeCount: 88,
      },
      {
        id: 10,
        title: 'Git & GitHub, 원리부터 차근차근 - 근본깃 [완성편]',
        writer: 'nickname2',
        price: 16000,
        techBookThumbnailUrl: '/images/education-image1.png',
        createdAt: '2020-11-11',
        likeCount: 1,
      },
    ],
    pageNo: 0,
    pageSize: 16,
    totalElements: 10,
    totalPages: 1,
    hasNext: false,
    hasPrevious: false,
    first: true,
    last: true,
  },
};

export default item;
